// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MyCompany.Crm.Sales.Database.Migrations
{
    [DbContext(typeof(SalesCrudDbContext))]
    partial class SalesCrudDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MyCompany.Crm.Sales.Orders.OrderHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ClientId");

                    b.HasKey("Id");

                    b.ToTable("OrderHeaders");
                });

            modelBuilder.Entity("MyCompany.Crm.Sales.Orders.OrderNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedOn");

                    b.Property<Guid>("AuthorId");

                    b.Property<Guid?>("OrderHeaderId");

                    b.Property<Guid>("OrderId");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("OrderHeaderId");

                    b.ToTable("OrderNotes");
                });

            modelBuilder.Entity("MyCompany.Crm.Sales.Orders.OrderHeader", b =>
                {
                    b.OwnsOne("MyCompany.Crm.Sales.Orders.InvoicingDetails", "InvoicingDetails", b1 =>
                        {
                            b1.Property<Guid>("OrderHeaderId");

                            b1.Property<string>("Name");

                            b1.Property<string>("TaxId");

                            b1.HasKey("OrderHeaderId");

                            b1.ToTable("OrderHeaders");

                            b1.HasOne("MyCompany.Crm.Sales.Orders.OrderHeader")
                                .WithOne("InvoicingDetails")
                                .HasForeignKey("MyCompany.Crm.Sales.Orders.InvoicingDetails", "OrderHeaderId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("MyCompany.Crm.Sales.Orders.OrderNote", b =>
                {
                    b.HasOne("MyCompany.Crm.Sales.Orders.OrderHeader")
                        .WithMany("Notes")
                        .HasForeignKey("OrderHeaderId");
                });
#pragma warning restore 612, 618
        }
    }
}
