name: Imaging Cloud Analyzer Action
env:
  version: 1
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  run-imaging-cloud-analyzer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Imaging Cloud Action
        run: |
          cd ${{github.workspace}}
          docker run -v $(pwd):/home/carl/extras/source -e IMAGING_CLOUD_API_KEY=${{secrets.IMAGING_CLOUD_API_KEY}} -e REPO_URL=${{github.server_url}}/${{github.repository}} -e BRANCH_NAME=${{github.ref_name}} -e COMMIT_ID=${{github.sha}} -e IMAGING_CLOUD_ACTION_FILE_VERSION=${{env.version}} castimaging/imaging-cloud-action:latest